management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: "https://httpbin.org"
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: test
          uri: "https://httpbin.org"
          predicates:
            - Path=/add-header/**
          filters:
            - StripPrefix=1
            - AddHeader
