management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: "http://localhost:8585"
          predicates:
            - Path=/test
        - id: test
          uri: "http://localhost:8585"
          predicates:
            - Path=/add-header
          filters:
            - AddHeader
