management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${sso.issuer-uri}
        registration:
          sso:
            provider: sso
            client-id: ${sso.client-id}
            client-secret: ${sso.client-secret}
            scope: ${sso.scope}
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      routes:
        - id: test
          uri: "http://localhost:8585"
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: add-header
          uri: "http://localhost:8585"
          predicates:
            - Path=/headers
          filters:
            - AddHeader
        - id: json
          uri: "http://localhost:8585"
          predicates:
            - Path=/json
          filters:
            - RewriteJsonResponseBody=slideshow.title:Spring IO 2023,slideshow.slides[0].title:Hello World!
        - id: authorized
          uri: "http://localhost:8585"
          predicates:
            - Path=/token/**
          filters:
            - StripPrefix=1
            - Authorize
            - ExtractClaim=name,X-CLAIM-NAME
        - id: no-token
          uri: "http://localhost:8585"
          predicates:
            - Path=/no-token/**
          filters:
            - StripPrefix=1
            - ExtractClaim=name,X-CLAIM-NAME
